backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Hero Carousel"
        name: "hero"
        file: "content/homepage.json"
        fields:
          - label: "Slide 1"
            name: "slide1"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button Text", name: "button", widget: "string"}
          
          - label: "Slide 2"
            name: "slide2"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button Text", name: "button", widget: "string"}
          
          - label: "Slide 3"
            name: "slide3"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Button Text", name: "button", widget: "string"}

  - name: "contact"
    label: "Contact Info"
    files:
      - label: "Contact Details"
        name: "contact"
        file: "content/contact.json"
        fields:
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}

  - name: "testimonials"
    label: "Testimonials"
    files:
      - label: "All Testimonials"
        name: "testimonials"
        file: "content/testimonials.json"
        fields:
          - label: "Testimonials List"
            name: "items"
            widget: "list"
            fields:
              - {label: "Quote", name: "quote", widget: "text"}
              - {label: "Author", name: "author", widget: "string"}
